import './globals.css'
import Navbar from './Navbar'

export const metadata = {
  title: 'Ejercicio Practico 4.1 | Javier López Velasco',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="">
        <Navbar></Navbar>
        {children}</body>
    </html>
  )
}
